---
apiVersion: verify.gov.uk/v1beta1
kind: CertificateRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: verify-root-ca-new-crypto-spec
  namespace: {{ .Release.Namespace }}
spec:
  countryCode: GB
  commonName: Verify Root CA New Crypto Spec
  expiryMonths: 120
  organization: Cabinet Office
  organizationUnit: GDS
  location: London
  CACert: true
